version: '3.8'

services:
  db:
    image: postgres:13
    container_name: library_db
    environment:
      - POSTGRES_DB=librarydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - library-network

  app:
    container_name: library_app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=librarydb
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres_data:
